# Active Lesson Configuration
# This file is automatically generated by build.bat

# ============= 1. Getting Started =============

# file(GLOB_RECURSE SOURCE_FILE "src/1-getting-started/1-hello-window/*.cpp")

# set(SOURCE_FILE "src/1-getting-started/2-hello-triangle/2.1-hello-triangle.cpp")
# set(SOURCE_FILE "src/1-getting-started/2-hello-triangle/2.2-hello-rectangle.cpp")
# set(SOURCE_FILE "src/1-getting-started/2-hello-triangle/2.3-hello-triangles-colors.cpp")
# set( SOURCE_FILE "src/1-getting-started/2-hello-triangle/2.3-theCherno/res/2.1-hello-triangle-red.cpp")

# file(GLOB_RECURSE SOURCE_FILE "src/1-getting-started/3-shaders/3.1-cherno/res/*.cpp")
# file(GLOB_RECURSE SOURCE_FILE "src/1-getting-started/3-shaders/3.2-basic-shaders/*.cpp")
# file(GLOB_RECURSE SOURCE_FILE "src/1-getting-started/3-shaders/3.3-interpolation-uniforms/*.cpp")

# file(GLOB_RECURSE SOURCE_FILE "src/1-getting-started/3.5-abstracting/*.cpp")

# file(GLOB_RECURSE SOURCE_FILE "src/1-getting-started/4-textures/*.cpp")

# file(GLOB_RECURSE SOURCE_FILE "src/1-getting-started/5-transformations/5.1-maths/*.cpp")
# file(GLOB_RECURSE SOURCE_FILE "src/1-getting-started/5-transformations/5.2-projection-matrices/*.cpp")
# file(GLOB_RECURSE SOURCE_FILE "src/1-getting-started/5-transformations/5.3-rendering-multiple-objects/*.cpp")
# file(GLOB_RECURSE SOURCE_FILE "src/1-getting-started/5-transformations/5.4-pyramid/*.cpp")
# file(GLOB_RECURSE SOURCE_FILE "src/1-getting-started/5-transformations/5.5-cube/*.cpp")
# file(GLOB_RECURSE SOURCE_FILE "src/1-getting-started/5-transformations/5.6-test-framework/*.cpp")
# file(GLOB_RECURSE SOURCE_FILE "src/1-getting-started/5-transformations/5.7-more-cubes/*.cpp")

# file(GLOB_RECURSE SOURCE_FILE "src/1-getting-started/6-camera/6.1-camera-class/*.cpp")
# file(GLOB_RECURSE SOURCE_FILE "src/1-getting-started/6-camera/6.2-optimization/*.cpp")

# ============= 2. Lighting =============

# file(GLOB_RECURSE SOURCE_FILE "src/2-lighting/1-colors-and-2-basic-lighting/1.1-crazy-sun/*.cpp")
file(GLOB_RECURSE SOURCE_FILE "src/2-lighting/1-colors-and-2-basic-lighting/1.2-orbiting-cubes/*.cpp")